### ISSUE TITLE
Update usage example

### ISSUE THREAD

**Issue by AlanFoster** [yanivkalfa/snowplow-react-native-tracker#1]
The `readme.md` is currently out of date. If I understand correctly the usage is now more similar to:

```js
import * as snowplow from 'snowplow-react-native-tracker';

const emitter = snowplow.Emitter({
  endpoint: 'myscalastreamcollector.net', // Collector endpoint
  protocol: 'http', // Optionally specify a protocol - http is the default
  port: 8080, // Optionally specify a port
  method: 'POST', // Method - defaults to GET
  bufferSize: 5, // Only send events once n are buffered. Defaults to 1 for GET requests and 10 for POST requests.
});

const tracker = snowplow.Tracker({
  emitters: [emitter], // One or more emitters associated with this tracker
  namespace: 'newTracker', // The namespace of the tracker
  appId: 'your-app-id', // The tracker id
  encodeBase64: true // defaults to true
});
```

After creation the API usage is as expected:

```js
tracker.trackStructEvent(
 category,
 action,
 label,
 property,
 value
);
```

**Comment by yanivkalfa** [comment]
I am not sure what exactly did you change however this package is just a wrapper around the original.

**Comment by cdimitroulas** [comment]
Alan is correct, importing it as per the readme file does not work and throws an error.
instead of 
```
import snowplow from 'snowplow-react-native-tracker';
```

it should be 
```
import * as snowplow from 'snowplow-react-native-tracker';
```

Also, in the original you use `snowplow.emitter` and `snowplow.tracker` whereas in this library they are capitalised (e.g. `snowplow.Emitter`).

**Comment by yanivkalfa** [comment]
fixed the import to be
```import snowplow from 'snowplow-react-native-tracker';```

Also change the capitalized names to none capitalize like the original

https://github.com/yanivkalfa/snowplow-react-native-tracker/blob/master/src/index.js

**Comment by sarneetk** [comment]
npm registry still has the old code with capitalised `Emitter` and `Tracker`
