### ISSUE TITLE
Port not correctly interpolated when collector contains root

### ISSUE THREAD

**Issue by AlanFoster** [yanivkalfa/snowplow-react-native-tracker#2]
Sometimes a collector URL may have an endpoint such as `example.com/snowplow_event_tracker`, which causes issues when interpolating the portString.

```js
const targetUrl = protocol + '://' + endpoint + portString + path;
```

i.e. Given the endpoint `example.com/snowplow_event_tracker`, the current logic will place the portString at the end to give `http://example.com/snowplow_event_tracker:8080/i` rather than the expected place `example.com:8080`

**Comment by yanivkalfa** [comment]
this package is just a wrapper for the original package. the issue your describing should be posted on their git.
